version: '3.8'

services:
  music-lyrics-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-lyrics-web
    restart: unless-stopped
    
    # 端口映射：将容器内部的 8080 端口映射到宿主机的 80 端口
    ports:
      - "10040:8080"
    
    # 环境变量
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 网络配置
    networks:
      - music-lyrics-network
    
    # 安全配置
    security_opt:
      - no-new-privileges:true
    
    # 只读根文件系统（除了必要的临时目录）
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    
    # 标签
    labels:
      - "com.example.description=Music Lyrics Web Application"
      - "com.example.version=1.0.0"
      - "com.example.maintainer=your-email@example.com"

networks:
  music-lyrics-network:
    driver: bridge

# 可选：如果需要持久化存储，可以添加 volumes 配置
# volumes:
#   nginx_logs:
#     driver: local